image:
  repository: registry.gitlab.com/seu-usuario/devops-server 
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

replicaCount: 1