# charts/devops-server/values.yaml
image:
  repository: registry.gitlab.com/mario_luz/desafio-devops # Substitua pelos seus dados
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi