apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kong
spec:
  replicas: 1
  serviceName: kong-proxy
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: proxy
        image: kong:3.3 # kong:3.6 não suporta cassandra apenas postgres
        command: ["/bin/bash", "/start.sh"]
        ports:
        - containerPort: 8000
        - containerPort: 8443
        - containerPort: 8100
        env:
        - name: KONG_DATABASE
          value: "cassandra"
        - name: KONG_CASSANDRA_CONTACT_POINTS
          value: "cassandra-0.cassandra.default.svc.cluster.local"
        - name: KONG_CASSANDRA_KEYSPACE
          value: "kong"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        - name: KONG_ADMIN_GUI_URL
          value: "http://desafio:8001"
        - name: KONG_ADMIN_SSL
          value: "false"
        # Executar como usuário não-root (opcional)
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: kong-data
          mountPath: /kong_prefix/
        - name: scripts # Novo volume para o script
          mountPath: /start.sh
          subPath: start.sh
      # Configurar o volume hostPath diretamente no pod
      volumes:
      - name: kong-data
        hostPath:
          path: /data/kong # Certifique-se de que este diretório existe e tem as permissões corretas
      - name: scripts
        configMap:
          name: kong-scripts
      restartPolicy: Always
