apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: cassandra 
spec:
  clusterName: "dc1"
  serverType: cassandra
  serverVersion: "4.0.3"
  size: 1 # Configurar para um único nó
  config:
    cassandra-yaml:
      num_tokens: 256
      authenticator: AllowAllAuthenticator
      authorizer: AllowAllAuthorizer 
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard # Ou o nome da sua classe de armazenamento
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi # Ajuste o tamanho conforme necessário