apiVersion: k8ssandra.io/v1alpha1  
kind: CassandraDatacenter           
metadata:
  name: meu-cassandra-datacenter
  namespace: default 
spec:
  clusterName: meu-cluster-cassandra
  serverType: "cassandra"
  serverVersion: "4.0.3"
  size: 1 #(cluster de 1 node :-) )
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard #classe de armazenamento????
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi # Tamanho do volume
