apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-server
  namespace: argocd # Ou o namespace onde você instalou o ArgoCD
spec:
  project: default
  source:
    repoURL: https://gitlab.com/mario_luz/desafio-devops.git
    targetRevision: main # Ou a branch onde você armazena o código
    path: charts/devops-server 
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Ou o namespace onde você quer implantar a aplicação