# Desabilita o controlador de ingress do Kong, pois você está usando o Ingress NGINX
ingressController:
  enabled: false

# Configura o Kong para usar o Cassandra como banco de dados
db_mode: cassandra

# Configurações do Cassandra (substitua pelos seus valores)
cassandra:
  contact_points:
    - "meu-cassandra-datacenter.k8ssandra-operator.svc.cluster.local" # Nome do seu CassandraDatacenter
  keyspace: kong # Nome do keyspace no Cassandra
  replication_factor: 1
  data_centers:
    - name: dc1
      replicas: 1

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false  # Se você não precisar de acesso HTTPS ao Kong Manager  